name: sync to huggingface

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: setup git lfs
        run: |
          git lfs install
          git lfs track "*.png"
          git lfs track "*.pbf"
          git lfs track "*.pmtiles"
          git lfs track "*.zip"

      - name: push to huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "gabriele@insidegubbio.com"
          git config --global user.name "insidegubbio ci"

          git config --global lfs.url "https://huggingface.co/spaces/gablilli/cartografo.git/info/lfs"

          git remote add huggingface https://gablilli:${HF_TOKEN}@huggingface.co/spaces/gablilli/cartografo

          GIT_LFS_SKIP_SMUDGE=1 git lfs push huggingface --all

          git push huggingface main --force
